obj-m += ejemplo_modulo.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

test:
	sudo dmesg -C
	sudo insmod ejemplo_modulo.ko
	sudo rmmod ejemplo_modulo
	sudo dmesg